version: "3.9"

services:
  web:
    build: .
    command: gunicorn yaet.wsgi:application --bind 0.0.0.0:8000
    env_file: .env
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - 8000

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume:
